version: 2
jobs:
  build:
    docker:
      - image: titusoss/titus-ci-builder
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/signal-wrapper
    steps:
      - checkout
      - run:
          name: gometalinter
          command: gometalinter --vendor --tests --vendored-linters  --disable=gotype --enable=unused --enable=goimports --enable=gofmt ./...

workflows:
  version: 2
  build:
    jobs:
      - build
