version: 2
jobs:
  build_and_test:
    docker:
      - image: titusoss/titus-ci-builder
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/signal-wrapper
    steps:
      - checkout
      - run gometalinter --vendor --tests --vendored-linters  --disable=gotype --enable=unused --enable=goimports --enable=gofmt ./...

