version: 2
jobs:
  lint:
    docker:
      - image: titusoss/titus-ci-builder
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/signal-wrapper
    steps:
      - checkout
      - run:
          name: install
          command: govendor install +local
      - run:
          name: gometalinter
          command: gometalinter --vendor --tests --vendored-linters  --disable=gotype --enable=unused --enable=goimports --enable=gofmt ./...
  build:
    docker:
      - image: titusoss/titus-ci-builder
    resource_class: xlarge
    working_directory: /go/src/github.com/Netflix/signal-wrapper
    steps:
      - checkout
      - run:
          name: install
          command: govendor install +local
      - run:
          name: mkdir
          command: mkdir bin/
      - run:
          name: build
          command: gox -osarch="linux/amd64" -osarch="darwin/amd64" -output="bin/signal-watcher-{{.OS}}-{{.Arch}}" -verbose .
      - store_artifacts:
          path: /go/src/github.com/Netflix/signal-wrapper/bin
      - persist_to_workspace:
          root: bin
          paths:
            - signal-watcher-linux-amd64
  test:
    docker:
      - image: python:3-stretch
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: place signal-wrapper binary
          command: mv /tmp/workspace/signal-watcher-linux-amd64 signal-watcher
      - run:
          name: tests
          command: ./test.sh

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
      - test:
          requires:
            - build